# Generated by Django 6.0.3 on 2026-03-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_method_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('details', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#2D5A5A', max_length=7)),
                ('secondary_color', models.CharField(default='#1E3E3E', max_length=7)),
                ('font_family', models.CharField(choices=[('serif', 'Classic Serif (Cormorant Garamond)'), ('sans', 'Modern Sans-Serif (Inter)'), ('playfair', 'Elegant Playfair Display')], default='serif', max_length=20)),
                ('theme_style', models.CharField(choices=[('classic', 'Classic Luxury'), ('minimal', 'Modern Minimalist'), ('bold', 'Bold & Contemporary')], default='classic', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS overrides for this store')),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('figma_link', models.URLField(blank=True, max_length=500, null=True)),
                ('figma_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('figma_last_sync', models.DateTimeField(blank=True, null=True)),
                ('figma_design_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
