# Generated by Django 6.0.3 on 2026-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_blogpost_store_category_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enable_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_stripe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_tabby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_tamara',
            field=models.BooleanField(default=False),
        ),
    ]
