# Generated by Django 6.0.3 on 2026-03-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_enable_cod_store_enable_stripe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('hero_bg', 'Homepage Hero Background'), ('men_collection', 'Men Collection Banner'), ('women_collection', 'Women Collection Banner'), ('about_hero', 'About Page Hero Banner'), ('contact_banner', 'Contact Page Background'), ('login_banner', 'Login/Registration Background'), ('nav_bg', 'Navigation Sidebar Background')], max_length=50)),
                ('image', models.ImageField(upload_to='frontend/')),
                ('title', models.CharField(blank=True, help_text='Optional overlay title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional overlay subtitle', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='store.store')),
            ],
            options={
                'verbose_name_plural': 'Frontend Media Assets',
                'unique_together': {('store', 'section_name')},
            },
        ),
    ]
