# Generated by Django 6.0.3 on 2026-03-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_frontendmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendmedia',
            name='section_name',
            field=models.CharField(choices=[('hero_slide_1', 'Homepage Hero Slide 1'), ('hero_slide_2', 'Homepage Hero Slide 2'), ('hero_slide_3', 'Homepage Hero Slide 3'), ('men_collection', 'Men Collection Banner'), ('women_collection', 'Women Collection Banner'), ('about_hero', 'About Page Hero Banner'), ('contact_banner', 'Contact Page Background'), ('login_banner', 'Login/Registration Background'), ('nav_bg', 'Navigation Sidebar Background')], max_length=50),
        ),
    ]
