# Generated by Django 6.0.3 on 2026-03-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_external_url',
            field=models.URLField(blank=True, help_text='External URL for product image (if no file uploaded)', max_length=500, null=True),
        ),
    ]
