# Generated by Django 6.0.3 on 2026-03-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_bogooffer_categoryoffer_offersection_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.CharField(blank=True, help_text='e.g. Amber, Sandalwood', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.CharField(blank=True, help_text='e.g. Agarwood, Patchouli', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, help_text='e.g. Saffron, Rose', max_length=255, null=True),
        ),
    ]
