# Generated by Django 6.0.3 on 2026-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_servicehighlight_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_external_url',
            field=models.URLField(blank=True, help_text='External URL for blog image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_external_url',
            field=models.URLField(blank=True, help_text='External URL for brand image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_external_url',
            field=models.URLField(blank=True, help_text='External URL for category image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='frontendmedia',
            name='image_external_url',
            field=models.URLField(blank=True, help_text="External URL for this section's media", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image_external_url',
            field=models.URLField(blank=True, help_text='External URL for store logo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='frontendmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/'),
        ),
    ]
