# Generated by Django 6.0.3 on 2026-03-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_image_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOGOOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bogo_type', models.CharField(choices=[('b1g1_free', 'Buy 1 Get 1 Free'), ('b2g1', 'Buy 2 Get 1 Free'), ('b1g1_half', 'Buy 1 Get 1 at 50% Off'), ('b3g1', 'Buy 3 Get 1 Free'), ('b2g2', 'Buy 2 Get 2 Free')], default='b1g1_free', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bogo/')),
                ('image_external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('cta_text', models.CharField(default='Shop Now', max_length=80)),
                ('cta_url', models.CharField(default='/products/', max_length=500)),
                ('bg_color', models.CharField(default='#0d2626', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Leave blank to apply to all categories', related_name='bogo_offers', to='store.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Leave blank to apply to all products', related_name='bogo_offers', to='store.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bogo_offers', to='store.store')),
            ],
            options={
                'verbose_name': 'BOGO Offer',
                'verbose_name_plural': 'BOGO Offers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('discount_label', models.CharField(blank=True, help_text="E.g. 'Up to 25% Off'", max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_offers/')),
                ('image_external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cta_text', models.CharField(default='Shop Now', max_length=80)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('bg_color', models.CharField(default='#1a3535', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='store.store')),
            ],
            options={
                'verbose_name': 'Category Offer',
                'verbose_name_plural': 'Category Offers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfferSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('percent', 'Percentage Discount'), ('flat', 'Flat Amount Off'), ('free_ship', 'Free Shipping'), ('gift', 'Free Gift'), ('bogo', 'Buy 1 Get 1'), ('bundle', 'Bundle Deal')], default='percent', max_length=20)),
                ('discount_value', models.FloatField(default=0, help_text='Discount % or flat amount')),
                ('promo_code', models.CharField(blank=True, help_text='Coupon code to display', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('image_external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cta_text', models.CharField(default='Claim Offer', max_length=80)),
                ('cta_url', models.CharField(default='/products/', max_length=500)),
                ('badge_text', models.CharField(blank=True, help_text="E.g. 'LIMITED TIME'", max_length=50)),
                ('bg_color', models.CharField(default='#2D5A5A', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Countdown timer end time', null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_sections', to='store.store')),
            ],
            options={
                'verbose_name': 'Offer Section',
                'verbose_name_plural': 'Offer Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('badge_text', models.CharField(blank=True, help_text="E.g. 'NEW', 'HOT DEAL'", max_length=50)),
                ('cta_text', models.CharField(default='Shop Now', max_length=80)),
                ('cta_url', models.CharField(default='/products/', help_text='Link for the CTA button', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(choices=[('top', 'Top Banner (Full Width)'), ('mid', 'Mid-Page Banner'), ('bottom', 'Bottom Banner')], default='top', max_length=10)),
                ('bg_color', models.CharField(default='#1E3E3E', help_text='Fallback background hex color', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_banners', to='store.store')),
            ],
            options={
                'verbose_name': 'Promo Banner',
                'verbose_name_plural': 'Promo Banners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
