# Generated by Django 6.0.3 on 2026-03-23 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='store.store'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='position',
            field=models.CharField(choices=[('top', 'Top Hero Slider'), ('mid_large', 'Mosaic Large Banner'), ('mid_small', 'Mosaic Small Grid'), ('bottom_tall', 'Bottom Side Tall'), ('bottom_wide', 'Bottom Side Wide')], default='top', max_length=20),
        ),
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Store', max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_section', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon_class', models.CharField(default='ph ph-truck', help_text='Phosphor icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='store.store')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
