# Generated by Django 6.0.3 on 2026-03-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_brand_is_featured_alter_brand_name_alter_brand_store_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeaboutsection',
            options={'verbose_name': 'Home About Section', 'verbose_name_plural': 'Home About Sections'},
        ),
        migrations.AlterModelOptions(
            name='servicehighlight',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Service Highlight', 'verbose_name_plural': 'Service Highlights'},
        ),
        migrations.AddField(
            model_name='homeaboutsection',
            name='image_external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hp_about', to='store.store'),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='title',
            field=models.CharField(default='A Legacy of Pure Elegance', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='icon_class',
            field=models.CharField(choices=[('ph ph-truck', 'Truck (Delivery)'), ('ph ph-shield-check', 'Shield (Secure)'), ('ph ph-headphones', 'Headphones (Support)'), ('ph ph-package', 'Package (Packing)'), ('ph ph-credit-card', 'Credit Card (Payments)'), ('ph ph-seal-check', 'Seal (Authentic)'), ('ph ph-globe', 'Globe (Global)'), ('ph ph-clock', 'Clock (Fast)')], default='ph ph-truck', max_length=60),
        ),
    ]
