# Generated by Django 6.0.3 on 2026-03-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_homeaboutsection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicehighlight',
            name='store',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='position',
            field=models.CharField(choices=[('top', 'Top Banner (Full Width)'), ('mid', 'Mid-Page Banner'), ('bottom', 'Bottom Banner')], default='top', max_length=10),
        ),
        migrations.DeleteModel(
            name='HomeAboutSection',
        ),
        migrations.DeleteModel(
            name='ServiceHighlight',
        ),
    ]
