# Generated by Django 6.0.3 on 2026-03-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_blogpost_image_external_url_brand_image_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogooffer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bogo_offers', to='store.store'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='store.store'),
        ),
        migrations.AlterField(
            model_name='frontendmedia',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='store.store'),
        ),
        migrations.AlterField(
            model_name='offersection',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_sections', to='store.store'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_banners', to='store.store'),
        ),
    ]
