# Generated by Django 6.0.3 on 2026-03-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_bogooffer_store_alter_categoryoffer_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_1_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_1_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_2_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_2_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_3_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_3_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_4_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_stat_4_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='heritage_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='promo_ticker_badge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='promo_ticker_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='promo_ticker_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='frontendmedia',
            name='section_name',
            field=models.CharField(choices=[('hero_slide_1', 'Homepage Hero Slide 1'), ('hero_slide_2', 'Homepage Hero Slide 2'), ('hero_slide_3', 'Homepage Hero Slide 3'), ('men_collection', 'Men Collection Banner'), ('women_collection', 'Women Collection Banner'), ('about_hero', 'About Page Hero Banner'), ('contact_banner', 'Contact Page Background'), ('login_banner', 'Login/Registration Background'), ('nav_bg', 'Navigation Sidebar Background'), ('heritage_bg', 'Heritage Section Background'), ('footer_bg', 'Footer Background')], max_length=50),
        ),
    ]
