# Generated by Django 6.0.3 on 2026-03-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_store_contact_address_store_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
