# Generated by Django 6.0.3 on 2026-03-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferSection',
        ),
    ]
