# Generated by Django 6.0.3 on 2026-03-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_delete_offersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendmedia',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Button text', max_length=50),
        ),
        migrations.AddField(
            model_name='frontendmedia',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Button link URL', max_length=500),
        ),
        migrations.AddField(
            model_name='frontendmedia',
            name='label',
            field=models.CharField(blank=True, help_text="Small label text (e.g. 'DISCOVER')", max_length=100),
        ),
        migrations.AlterField(
            model_name='frontendmedia',
            name='section_name',
            field=models.CharField(choices=[('hero_slide_1', 'Homepage Hero Slide 1'), ('hero_slide_2', 'Homepage Hero Slide 2'), ('hero_slide_3', 'Homepage Hero Slide 3'), ('collection_hero', 'Products Listing Hero Banner'), ('men_collection', 'Men Collection Banner'), ('women_collection', 'Women Collection Banner'), ('about_hero', 'About Page Hero Banner'), ('contact_banner', 'Contact Page Background'), ('login_banner', 'Login/Registration Background'), ('nav_bg', 'Navigation Sidebar Background'), ('heritage_bg', 'Heritage Section Background'), ('footer_bg', 'Footer Background')], max_length=50),
        ),
        migrations.AlterField(
            model_name='frontendmedia',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional description or subheading', max_length=500),
        ),
        migrations.AlterField(
            model_name='frontendmedia',
            name='title',
            field=models.CharField(blank=True, help_text='Main heading text', max_length=200),
        ),
    ]
