# Generated by Django 6.0.3 on 2026-03-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_frontendmedia_cta_text_frontendmedia_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category_section_subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='category_section_title',
            field=models.CharField(blank=True, default='Shop by Category', max_length=200),
        ),
    ]
