# Generated by Django 6.0.3 on 2026-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_store_category_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category_offers_subtitle',
            field=models.CharField(blank=True, default='Shop by Deal', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='category_offers_title',
            field=models.CharField(blank=True, default='Category Offers', max_length=200),
        ),
    ]
