# Generated by Django 6.0.3 on 2026-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_store_category_offers_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bogo_section_label',
            field=models.CharField(blank=True, default='Best Value', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='bogo_section_subtitle',
            field=models.CharField(blank=True, default='Double the luxury without doubling the spend.', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='bogo_section_title',
            field=models.CharField(blank=True, default='Buy One, Get One Deals', max_length=200),
        ),
    ]
